openapi: 3.0.0
info:
  title: Random Bell Scheduler API
  version: 1.0.0
  description: Local API contracts for random bell scheduling system

paths:
  /scheduler/generate:
    post:
      summary: Generate random bell schedule for a date range
      operationId: generateSchedule
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                startDate:
                  type: string
                  format: date
                endDate:
                  type: string
                  format: date
                density:
                  $ref: '#/components/schemas/BellDensity'
                activeWindows:
                  type: array
                  items:
                    $ref: '#/components/schemas/TimeWindow'
                quietHours:
                  type: array
                  items:
                    $ref: '#/components/schemas/TimeWindow'
                minimumInterval:
                  type: integer
                  description: Minimum minutes between bells
                  default: 45
              required: [startDate, endDate, density, activeWindows]
      responses:
        '200':
          description: Schedule generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  schedule:
                    type: array
                    items:
                      $ref: '#/components/schemas/ScheduledBell'
                  metadata:
                    $ref: '#/components/schemas/ScheduleMetadata'

  /scheduler/validate:
    post:
      summary: Validate schedule parameters without generating
      operationId: validateScheduleParams
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                density:
                  $ref: '#/components/schemas/BellDensity'
                activeWindows:
                  type: array
                  items:
                    $ref: '#/components/schemas/TimeWindow'
                quietHours:
                  type: array
                  items:
                    $ref: '#/components/schemas/TimeWindow'
                minimumInterval:
                  type: integer
              required: [density, activeWindows]
      responses:
        '200':
          description: Parameters are valid
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
                  estimatedBellsPerDay:
                    type: integer
                  availableMinutesPerDay:
                    type: integer
                  warnings:
                    type: array
                    items:
                      type: string

  /scheduler/cleanup:
    post:
      summary: Clean up expired scheduled bells
      operationId: cleanupExpiredBells
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cutoffTime:
                  type: string
                  format: date-time
                  description: Remove bells scheduled before this time
              required: [cutoffTime]
      responses:
        '200':
          description: Cleanup completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  removedCount:
                    type: integer
                  remainingCount:
                    type: integer

  /notifications/schedule:
    post:
      summary: Schedule system notifications for bells
      operationId: scheduleNotifications
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                bells:
                  type: array
                  items:
                    $ref: '#/components/schemas/ScheduledBell'
                soundConfig:
                  $ref: '#/components/schemas/SoundConfig'
              required: [bells]
      responses:
        '200':
          description: Notifications scheduled
          content:
            application/json:
              schema:
                type: object
                properties:
                  scheduled:
                    type: array
                    items:
                      type: object
                      properties:
                        bellId:
                          type: string
                        notificationId:
                          type: string
                        status:
                          type: string
                          enum: [scheduled, failed, skipped]
                  limitations:
                    type: object
                    properties:
                      maxPendingReached:
                        type: boolean
                      platformLimit:
                        type: integer

  /notifications/cancel:
    post:
      summary: Cancel scheduled notifications
      operationId: cancelNotifications
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                notificationIds:
                  type: array
                  items:
                    type: string
                bellIds:
                  type: array
                  items:
                    type: string
                  description: Alternative to notification IDs - cancel by bell ID
      responses:
        '200':
          description: Notifications cancelled
          content:
            application/json:
              schema:
                type: object
                properties:
                  cancelledCount:
                    type: integer
                  failedCount:
                    type: integer

components:
  schemas:
    BellDensity:
      type: string
      enum: [low, medium, high]
      description: |
        - low: ~4 bells per day (6-hour average interval)
        - medium: ~8 bells per day (3-hour average interval)
        - high: ~12 bells per day (2-hour average interval)

    TimeWindow:
      type: object
      properties:
        start:
          type: string
          format: time
          pattern: '^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$'
          example: "09:00"
        end:
          type: string
          format: time
          pattern: '^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$'
          example: "17:30"
      required: [start, end]

    ScheduledBell:
      type: object
      properties:
        id:
          type: string
          format: uuid
        scheduledTime:
          type: string
          format: date-time
        windowIndex:
          type: integer
          description: Which active window this bell falls within
        generatedAt:
          type: string
          format: date-time
        status:
          type: string
          enum: [pending, scheduled, triggered, acknowledged, missed, cancelled]
      required: [id, scheduledTime, windowIndex, generatedAt, status]

    ScheduleMetadata:
      type: object
      properties:
        generatedAt:
          type: string
          format: date-time
        dateRange:
          type: object
          properties:
            start:
              type: string
              format: date
            end:
              type: string
              format: date
        parameters:
          type: object
          properties:
            density:
              $ref: '#/components/schemas/BellDensity'
            totalActiveMinutes:
              type: integer
            minimumInterval:
              type: integer
        statistics:
          type: object
          properties:
            totalBells:
              type: integer
            bellsPerDay:
              type: number
            averageInterval:
              type: number
              description: Average minutes between bells
            distribution:
              type: array
              items:
                type: object
                properties:
                  date:
                    type: string
                    format: date
                  count:
                    type: integer

    SoundConfig:
      type: object
      properties:
        enabled:
          type: boolean
        soundFile:
          type: string
          nullable: true
          description: Path to custom sound file, null for default
        volume:
          type: number
          minimum: 0
          maximum: 1
          default: 0.8
        vibrationEnabled:
          type: boolean
        vibrationPattern:
          type: array
          items:
            type: integer
          description: Vibration pattern in milliseconds [on, off, on, ...]
      required: [enabled, vibrationEnabled]